config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :rooms
  resources :receipts
  resources :records

  root 'receipts#index'

  get 'print_receipt/:id', to: 'receipts#print'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tenant.rb
# == Schema Information
#
# Table name: tenants
#
#  id         :integer          not null, primary key
#  name       :string           default("张三"), not null
#  phone      :string
#  gov_id     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tenant < ApplicationRecord
  has_many :room_tenant_connections
  has_many :rooms, through: :room_tenant_connections

  def curr_room_number
    curr_room.number unless !curr_room
  end

  def curr_room
    curr_connection.room unless !curr_connection
  end

  def curr_connection
    room_tenant_connections.find_by(active:true)
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
    @tenants = Tenant.all
  end

  def new
    @tenant = Tenant.new
  end

  def edit
    @tenant = Tenant.find(params[:id])
  end

  def show
    @tenant = Tenant.find(params[:id])
  end

  def create
    @tenant = Tenant.new(tenant_params)

    if @tenant.save
      update_room
      redirect_to @tenant
    else
      render 'new'
    end
  end

  def update
    @tenant = Tenant.find(params[:id])
    update_room
    if @tenant.update_attributes(tenant_params)
      redirect_to @tenant
    else
      redirect_to 'edit'
    end
  end

  def destroy
    @tenant = Tenant.find(params[:id])
    @tenant.destroy

    redirect_to tenants_path
  end

  private
    def tenant_params
      params.require(:tenant).permit(:name, :phone)
    end

    def update_room
      number = params[:tenant][:curr_room_number]
      if number
        @tenant.curr_connection.update(active: false, is_admin: false) unless !@tenant.curr_connection
        @tenant.room_tenant_connections.create!(room_id: Room.find_by(number: number).id, active: true, is_admin: true)
      end
      rent = params[:tenant][:rooms][:rent]
      if rent && rent != @tenant.curr_room.rent
        @tenant.curr_room.update_attributes(rent: rent)
      end
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= form_for @tenant do |f| %>
  <% if @tenant.errors.any? %>
    <div id='eror_explanation'>
      <h2>该页面存在错误</h2>
        <%= pluralize(@tenant.errors.count, 'error')%>
        <ul>
          <% @tenant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
    <p>
      <%= f.label :房号 %>
      <%= f.text_field :curr_room_number %>
    </p>

    <p>
      <%= f.label :姓名 %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :手机 %>
      <%= f.text_field :phone %>
    </p>

    <p>
      <%= f.label :房租 %>
      <%= f.fields_for :rooms, @tenant.curr_room do |room_fields| %>
      <%= room_fields.text_field :rent %>
      <% end %>
    </p>

    <p>
      <%= f.submit '保存' %>
    </p>
<% end %>

app/views/tenants/edit.html.erb
<h1>修改资料</h1>
<%= render 'form' %>
<%= link_to '返回', root_path %>

app/views/tenants/index.html.erb
<h1>所有房客</h2>
  <%= link_to '76号', controller: 'tenants' %>
<table>
  <tr>
    <th>房号</th>
    <th>姓名</th>
  </tr>

  <% @tenants.each do |t| %>
    <tr>
      <td><%= t.room %></td>
      <td><%= t.name %></td>
      <td><%= link_to '详情', tenant_path(t) %></td>
      <td><%= link_to '修改', edit_tenant_path(t) %></td>
      <td><%= link_to '删除', tenant_path(t), method: :delete,
        data: { confirm: '是否确定删除改房客？' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to '新建', new_tenant_path %>

app/views/tenants/new.html.erb
<%= render 'form'%>
<%= link_to '返回', tenants_path  %>

app/views/tenants/show.html.erb
<p>
  <strong>房号:</strong>
  <%= @tenant.curr_room_number%>
</p>

<p>
  <strong>姓名:</strong>
  <%= @tenant.name%>
</p>

<p>
  <strong>手机:</strong>
  <%= @tenant.phone%>
</p>

<p>
  <strong>房租:</strong>
  <%= @tenant.curr_room.rent%>
</p>
<%= link_to '修改', edit_tenant_path(@tenant)  %>
<%= link_to '返回', root_path %>