config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :rooms
  resources :receipts
  resources :records

  root 'receipts#index'

  get 'print_receipt/:id', to: 'receipts#print'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/record.rb
# == Schema Information
#
# Table name: records
#
#  id                     :integer          not null, primary key
#  date                   :datetime         default(Mon, 12 Feb 2018 12:26:51 UTC +00:00), not null
#  pre_water_count        :decimal(, )      default(0.0), not null
#  current_water_count    :decimal(, )      default(0.0), not null
#  pre_ele_count          :decimal(, )      default(0.0), not null
#  current_ele_count      :decimal(, )      default(0.0), not null
#  internet_fee           :decimal(, )      default(0.0), not null
#  tv_fee                 :decimal(, )      default(0.0), not null
#  cleaning_fee           :decimal(, )      default(0.0), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  room_id                :integer
#  tenant_id              :integer
#  receipt_id             :integer
#  pre_moto_ele_count     :decimal(, )
#  current_moto_ele_count :decimal(, )
#

class Record < ApplicationRecord
  belongs_to :room
  belongs_to :receipt

  def total_fee
    if with_tenant?
      moto_ele_fee + ele_fee + water_fee + tv_fee + internet_fee + room.rent + 10 # 10 is for cleaning
    else
      0
    end
  end

  def rent_fee
    room.rent
  end

  def ele_fee
    used_ele_count * receipt.electricity_rate.rate
  end

  def moto_ele_fee
    used_moto_ele_count * receipt.moto_electricity_rate.rate
  end

  def water_fee
    used_water_count * receipt.water_rate.rate
  end

  def used_water_count
    current_water_count - pre_water_count
  end

  def used_ele_count
    current_ele_count - pre_ele_count
  end
  
  def used_moto_ele_count
    current_moto_ele_count - pre_moto_ele_count
  end

  private
  def with_tenant?
    moto_ele_fee + ele_fee + water_fee > 0
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def show
    @record = Record.find(params[:id])
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      redirect_to @record
    else
      render 'edit'
    end
  end

  private
    def record_params
      params.require(:record).permit(:current_moto_ele_count, :current_ele_count, :current_water_count, :pre_moto_ele_count, :pre_ele_count, :pre_water_count)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for :record, url: record_path(@record), method: :patch do |f| %>
<% if @record.errors.any? %>
  <div id='eror_explanation'>
    <h2>该页面存在错误</h2>
      <%= pluralize(@record.errors.count, 'error')%>
      <ul>
        <% @record.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>
  <p>
    <%= f.label :上月水吨数 %>
    <%= f.text_field :pre_water_count %>
  </p>

  <p>
    <%= f.label :本月水吨数 %>
    <%= f.text_field :current_water_count %>
  </p>

  <p>
    <%= f.label :上月电度数 %>
    <%= f.text_field :pre_ele_count %>
  </p>

  <p>
    <%= f.label :本月电度数 %>
    <%= f.text_field :current_ele_count %>
  </p>

  <p>
    <%= f.label :上月电动车电度数 %>
    <%= f.text_field :pre_moto_ele_count %>
  </p>

  <p>
    <%= f.label :本月电动车电度数 %>
    <%= f.text_field :current_moto_ele_count %>
  </p>

  <p>
    <%= f.submit '保存' %>
  </p>
<% end %>

app/views/records/edit.html.erb
<h1>修改水电</h1>
<%= render 'form' %>
<%= link_to '返回', root_path %>

app/views/records/show.html.erb
<style type="text/css" media="screen">

table{
border-collapse:collapse;
border:1px solid black;
}

table td, th{
border:1px solid black;
padding: 5px;
text-align:center;
}
</style>
<table>
  <tr>
    <th>上月水吨数</th>
    <th>本月水吨数</th>
    <th>上月电度数</th>
    <th>本月电度数</th>
    <th>上月电动车电度数</th>
    <th>本月电动车电度数</th>
  </tr>
  <tr>
    <td><%= @record.pre_water_count%></td>
    <td><%= @record.current_water_count%></td>
    <td><%= @record.pre_ele_count%></td>
    <td><%= @record.current_ele_count%></td>
    <td><%= @record.pre_moto_ele_count%></td>
    <td><%= @record.current_moto_ele_count%></td>
  </tr>
</table>
<%= link_to '修改', edit_record_path(@record)  %>
<%= link_to '返回', root_path %>