config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :rooms
  resources :receipts
  resources :records

  root 'receipts#index'

  get 'print_receipt/:id', to: 'receipts#print'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/receipt.rb
# == Schema Information
#
# Table name: receipts
#
#  id         :integer          not null, primary key
#  date       :datetime         default(Mon, 12 Feb 2018 12:26:51 UTC +00:00), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Receipt < ApplicationRecord
  has_many :records
  has_one :water_rate
  has_one :electricity_rate
  has_one :moto_electricity_rate
  after_create :create_records, :create_rates
  accepts_nested_attributes_for :records, :water_rate, :electricity_rate, :moto_electricity_rate

  def self.get_receipt(getDate)
    receipts = Receipt.select{|r| r.date.year == getDate.year && r.date.month == getDate.month}
    receipts.count > 0 ? receipts.first : Receipt.create!(date:getDate)
  end

  def total_ele
    records.map(&:ele_fee).sum
  end

  def total_water
    records.map(&:water_fee).sum
  end

  def total_moto_ele
    records.map(&:moto_ele_fee).sum
  end

  def total_rent
    records.map(&:rent_fee).sum
  end

  def total
    records.map(&:total_fee).sum
  end

  private
    def create_records
      date = Date.today
      Room.all.each do |room|
        record = room.curr_record(date)
        record.update_attributes!(receipt: self) unless record.receipt == self
      end
    end

    def create_rates
      create_water_rate
      create_ele_rate
      create_moto_ele_rate
    end

    def create_water_rate
      rate = WaterRate.last ? WaterRate.last.rate : 0
      WaterRate.create!(rate:rate, date: date, receipt_id: id)
    end

    def create_ele_rate
      rate = ElectricityRate.last ? ElectricityRate.last.rate : 0
      ElectricityRate.create!(rate:rate, date: date, receipt_id: id)
    end

    def create_moto_ele_rate
      # rate = MotoElectricityRate.last ? MotoElectricityRate.last.rate : 0
      rate = 0
      MotoElectricityRate.create!(rate:rate, date: date, receipt_id: id)
    end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    @receipts = Receipt.all
  end

  def show
    @receipt = Receipt.find(params[:id])
  end

  def new
    @receipt = Receipt.create!(date:Date.today)
    get_room_data
    render "edit"
  end

  def edit
    @receipt = Receipt.find(params[:id])
    get_room_data
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy!
    redirect_to receipts_path
  end

  def update
    @receipt = Receipt.find(params[:id])
    if @receipt.update_attributes(receipt_params)
      redirect_to @receipt
    else
      render 'index'
    end
  end

  def print
    @receipt = Receipt.find(params[:id])
    @print_month = @receipt.date.month
    @print_year = @receipt.date.month < 12 ? @receipt.date.year : @receipt.date.year + 1
    @print_month = @receipt.date.month < 12 ? @receipt.date.month + 1 : 1
  end

  private
    def get_room_data
      @room_data = {}
      Room.all.each do |room|
        @room_data[room.number] = {
          tenant_path: room.admin_tenant ? edit_tenant_path(room.admin_tenant) : new_tenant_path,
          tenant_path_name: room.admin_tenant ? '修改房客资料' : '新建房客',
          admin_tenant: room.admin_tenant,
          rent: room.rent,
        }
      end
    end

    def receipt_params
      update_params = params.require(:receipt).permit(
        records_attributes: [:id, :pre_moto_ele_count, :current_moto_ele_count, :pre_ele_count, :current_ele_count, :pre_water_count, :current_water_count, :internet_fee, :cleaning_fee, :tv_fee],
        water_rate_attributes: [:id, :rate],
        electricity_rate_attributes: [:id, :rate],
        moto_electricity_rate_attributes: [:id, :rate]
      )
      if date_provided?
        update_params.merge!(date: receipt_date)
      end
      update_params
    end

    def receipt_date
      r_date = params[:receipt][:date]
      Date.new(r_date[:year].to_i, r_date[:month].to_i, r_date[:date].to_i)
    end

    def date_provided?
      !params[:receipt][:date][:year].empty?
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<style type="text/css" media="screen">

table{
border-collapse:collapse;
border:1px solid black;
}

table td, th{
border:1px solid black;
padding: 5px;
text-align:center;
}
</style>
<%= form_for @receipt do |f| %>
<p>
  <strong>收据显示日期</strong>
  <%= f.fields_for :date do |ff| %>
  <%= ff.text_field :year, placeholder: "年"%>
  <%= ff.text_field :month, placeholder: "月"%>
  <%= ff.text_field :date, placeholder: "日"%>
  <% end %>
</p>
<p>
  <strong>水费单价:</strong>
  <%= f.fields_for :water_rate do |ff| %>
  <%= ff.text_field :rate%>
  <% end %>
</p>

<p>
  <strong>电费单价:</strong>
  <%= f.fields_for :electricity_rate do |ff| %>
  <%= ff.text_field :rate%>
  <% end %>
</p>
<table>
  <tr>
    <th>房号</th>
    <th>姓名</th>
    <th>房租</th>
    <th>上月水吨数</th>
    <th>本月水吨数</th>
    <th>上月电度数</th>
    <th>本月电度数</th>
    <th>网费</th>
    <th></th>
  </tr>
  <% @receipt.records.joins(:room).order('rooms.id').each do |record| %>
  <%= f.fields_for :records, record do |record_fields| %>
    <tr>
      <td><%= record.room.number %></td>
      <td><%= @room_data[record.room.number][:admin_tenant] ? @room_data[record.room.number][:admin_tenant].name : '-' %></td>
      <td><%= @room_data[record.room.number][:rent].to_f %></td>
      <td><%= record_fields.text_field :pre_water_count %></td>
      <td><%= record_fields.text_field :current_water_count %></td>
      <td><%= record_fields.text_field :pre_ele_count %></td>
      <td><%= record_fields.text_field :current_ele_count %></td>
      <td><%= record_fields.text_field :internet_fee %></td>
      <td><%= link_to @room_data[record.room.number][:tenant_path_name], @room_data[record.room.number][:tenant_path] %></td>
    </tr>
  <% end %>
  <% end %>
  </table>
  <p>
    <%= f.submit '保存' %>
  </p>
<% end %>

app/views/receipts/edit.html.erb
<%= render 'form'%>
<%= link_to '返回', root_path %>

app/views/receipts/index.html.erb
<h1>收据档案</h1>
<% @receipts.each do |receipt| %>
  <h3><%= receipt.date.year%>年<%=receipt.date.month%>月收据 &emsp;<%= link_to '详情', receipt_path(receipt) %>&emsp;<%= link_to '修改', edit_receipt_path(receipt) %>&emsp;<%= link_to '删除', receipt_path(receipt), method: :delete, data: { confirm: '是否确定删除该收据？' } %></h3>
<% end %>
<%= link_to '新建收据', new_receipt_path %>

app/views/receipts/print.html.erb
<% @receipt.records.joins(:room).order('rooms.id').each do |record| %>
<center><h2>收&nbsp;&nbsp;据</h2></center>
&emsp;&emsp;今收到<%= record.room.admin_tenant ? record.room.admin_tenant.name : '-' %> (电话: <%= record.room.admin_tenant ? record.room.admin_tenant.phone : '-' %>) 住<%= record.room.number%>号房，交来<%= @receipt.date.year%>年<%= @receipt.date.month%>月1日至<%= @receipt.date.year%>年<%= @receipt.date.month%>月<%= @receipt.date.end_of_month.day %>日，房租<%= record.rent_fee%>元。
上月电表度数: <%= record.pre_ele_count%>, 本月电表度数: <%= record.current_ele_count%>, 实用度数: <%= record.used_ele_count%>, 实收电费: <%= record.ele_fee%> 元。上月水表吨水: <%= record.pre_water_count %>, 本月水表吨数: <%= record.current_water_count%>, 实用吨数: <%= record.used_water_count%>, 实收水费: <%= record.water_fee%> 元。
上月电动车电表度数: <%= record.pre_moto_ele_count%>, 本月电动车电表度数: <%= record.current_moto_ele_count%>, 实用度数: <%= record.used_moto_ele_count%>, 电动车电费 <%= record.moto_ele_fee %>  元。网费: <%= record.internet_fee %> 元, 卫生费: 10 元,
共收人民币 <%= record.total_fee %> 元.<br>
提示: 每月必需5号前交租，否则停水停电。退房需提前一个月告知，否则押金不退。合约未满提前退房，押金不退。<br>
<%= @print_year %>年<%= @receipt.date.month %>月1日<br>
备注:<u>微信号：h13902504788</u><br><br>
<% end %>

app/views/receipts/show.html.erb
<style type="text/css" media="screen">

table{
border-collapse:collapse;
border:1px solid black;
}

table td, th{
border:1px solid black;
padding: 5px;
text-align:center;
}
</style>
<h1><%= "#{@receipt.date.year}年#{@receipt.date.month}月"%>收据</h1>
<p>
  <strong>水费单价:</strong>
  <%= @receipt.water_rate.rate.to_f%>
</p>

<p>
  <strong>电费单价:</strong>
  <%= @receipt.electricity_rate.rate.to_f%>
</p>
<p>
  <strong>电动车电费单价:</strong>
  <%= @receipt.moto_electricity_rate.rate.to_f%>
</p>
<table>
  <tr>
    <th>房号</th>
    <th>住客姓名</th>
    <th>房租</th>
    <th>上月水吨数</th>
    <th>本月水吨数</th>
    <th>使用水吨数</th>
    <th>上月电度数</th>
    <th>本月电度数</th>
    <th>使用电度数</th>
    <th>卫生费</th>
    <th>网费</th>
    <th>总费用</th>
  </tr>
  <% @receipt.records.joins(:room).order('rooms.id').each do |record|%>
  <tr>
    <td><%= record.room.number %></td>
    <td><%= record.room.admin_tenant ? record.room.admin_tenant.name : '-' %></td>
    <td><%= record.room.rent.to_f %></td>
    <td><%= record.pre_water_count.to_f %></td>
    <td><%= record.current_water_count.to_f %></td>
    <td><%= record.used_water_count.to_f%></td>
    <td><%= record.pre_ele_count.to_f %></td>
    <td><%= record.current_ele_count.to_f %></td>
    <td><%= record.used_ele_count.to_f%></td>
    <td><%= 10 %></td>
    <td><%= record.internet_fee.to_f%></td>
    <td><%= record.total_fee.to_f%></td>
  </tr>
  <% end %>
</table>
<br><br>
<span>总电费：</span><%= @receipt.total_ele.to_f%><br>
<span>总水费：</span><%= @receipt.total_water.to_f%><br>
<span>总房租：</span><%= @receipt.total_rent.to_f%><br>
<span>总收费：</span><%= @receipt.total.to_f%><br>
<br><br>
<%= link_to '修改', edit_receipt_path(@receipt) %>
<%= link_to '打印', {controller: 'receipts', action: 'print', id: @receipt}, target: '_blank'%>
<br><br>
<%= link_to '返回', root_path %>